source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "10.0"


target 'MWPhotoBrowser_Example' do
  pod "MWPhotoBrowser", :path => "../"
end

target 'MWPhotoBrowser_Tests' do
  pod "MWPhotoBrowser", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  # pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
